# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.11.0
_src_path: gl:znicholls/copier-core-python-repository
conda_release: false
email: zebedee.nicholls@climate-energy-college.org
include_cli: false
name: Zebedee Nicholls
notebook_based_docs: true
package_manager: uv
pandas_doctests: true
plot_dependencies: true
project_description_short: Core package for workflows for assessing the global climate
    implications of global emission scenarios, typically from IAMs.
project_name_human: Global Climate Assessment of Global Emission Scenarios
project_name_pip: gcages
project_name_python: gcages
project_url: https://github.com/openscm/gcages
track_lock_file: true
